stages:
  - test

deployement test:
  image: node:latest
  stage: test
  before_script:
    - npm install --prefix ./app 
  script:
    - cd ./app
    - npm start
    - curl http://localhost:3000
    